### ISSUE TITLE
Upgrade to version 6.3a

### ISSUE THREAD

**Issue by lpla** [meyayl/docker-languagetool#18]
Hi.

Seems like there is a minor bugfix upgrade named 6.3a to work around this issue: https://github.com/languagetool-org/languagetool/issues/9880

Probably it was built from this branch: https://github.com/languagetool-org/languagetool/tree/v6.3a

Could you update the GitHub code and the Docker image in Docker Hub with this release .zip (https://languagetool.org/download/LanguageTool-6.3a.zip) or with the equivalent 'stable' .zip symlink (https://languagetool.org/download/LanguageTool-stable.zip)?

**Comment by meyayl** [comment]
I started working on it exactly a week ago, the Dockerfile needed a slight modification. I don't recall exactly why I could build the image, but I will take a look at it over the weekend.

Thank you for reminding me!

**Comment by meyayl** [comment]
Seems something is wrong with the git package of alpine 3.19.0.
Image builds just fine with alpine 3.18.5.

**Comment by meyayl** [comment]
Updated image is available on Docker Hub.
