### ISSUE TITLE
Grammalecte API

### ISSUE THREAD

**Issue by smnwl** [meyayl/docker-languagetool#19]
Would it be possible to add Grammalecte to LanguageTool (by way of linking to the api of grammalecte-cli running in another docker container?
The option of linking Grammalecte and LanguageTool seems to be an option through Yunohost. I haven't seen it elswhere though, nor have I had the chance to try it myself. I do have grammalecte running in a container, and would be keen to try to have them work in tandem, should that be possible.

**Comment by meyayl** [comment]
Could you explain how Grammalecte is related to LanguageTool and guide me to documentation that explains how it's integrated?

**Comment by meyayl** [comment]
I am closing the issue, as there has been no update for 3 months.
