### ISSUE TITLE
Compose file for build or pull?

### ISSUE THREAD

**Issue by BaumiCoder** [meyayl/docker-languagetool#25]
I run the docker container with the compose file from the repository. I only downloaded the single yml file, like it is suggested in the Readme. But this leads to an error:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /my/path/to/yml/file/Dockerfile: no such file or directory
ERROR: Service 'languagetool' failed to build : Build failed
```
So I take a look in the yml file and remove the line and then it works.
```yml
build: .
```

I am not sure if I understand something wrong. Is the yml for building the image or for pulling the image from remote?

**Comment by BaumiCoder** [comment]
Thank you for the fast fix and the maintenance of this docker image.

**Comment by meyayl** [comment]
My pleasure!
