### ISSUE TITLE
LanguageTool languagetool-commandline & GUI

### ISSUE THREAD

**Issue by pj-connect** [meyayl/docker-languagetool#33]
It's not an issue per se, but is it possible to also use languagetool-commandline and/or languagetool with this container ?

**Comment by meyayl** [comment]
Can you provide more context?

**Comment by pj-connect** [comment]
Since my comment, I learned how to build a docker image.

So yes. When you download [LanguageTool-stable](https://languagetool.org/download/LanguageTool-stable.zip), there are tree components within the zip file : 

1. A server (languagetool-server.jar) ;
2. A cli app (languagetool-commandline.jar) ;
3. A GUI app (languagetool.jar).

I see that your docker image is strictly exposing the languagetool-server, but have all 3 components in the container. 

So I was going to ask you if it is possible to run the image as a server, but also as a cli and/or gui app. One use case, would be to start a server, and use the cli app. Maybe have an environment switch, which would select the appropriate component to run.

**Comment by meyayl** [comment]
The image comes with whatever is included in the release zip, but only aims to support the server use case.

Docker/Kubernetes provide mechanisms that
- allow to exec into a running container and execute arbitrary commands
- allow overriding the entrypoint script for new created container with an arbitrary command.

Is the gui app a desktop or webapp?  
What benefits does the cli provide, why do we need it?

I don't see myself digging into these topics, as the common use case is to provide the lt-server, which can be used by existing lt-clients.

Feel free to fork the project, and modify it to your needs :)

**Comment by pj-connect** [comment]
I'm just asking if it's possible to support other use cases than just exposing the server; I was misled by the presence of the two client jar. 

Mainly it's for usability & portability, as I could move the image to an offline system with everything installed in it, i.e.: some kind of spellchecking Swiss knife.

Overriding the entry point would far exceed my actual knowledge of Docker, so forking is out of question. As I see it, from what you're saying, the (or my) solution would rather be to create a client image that would, if possible, to expose both GUI and CLI as there are multiple possible use cases. 

While running a local server, I could use it from a client web browser extension when on the web or even a client LibreOffice extension, but also in a terminal with the CLI to spell checker text files. I'm even trying to make it work in Vim. The GUI (Desktop) can also be useful when I'm very lazy to quickly spellcheck text files (I started to use it few weeks ago).

All in all, I was just curious, as I was asserting if the image would serve my use cases needs and simplify my workflow.

**Comment by meyayl** [comment]
I didn't remember that the entrypoint script already executes container arguments as command. 
IF container arguments are used, they will be executed without running through all commands of the entrypoint script.

Example: lets say you want to list the directory content of the work directory:
```
docker run --rm -ti meyay/languagetool:latest ls
```
Instead of `ls` use whatever arguments you need

**Comment by pj-connect** [comment]
Interesting ! But, as I understand it, access to the host filesystem might just "complexify" a little bit the workflow. Indeed, Docker containers are isolated environments that run applications with their own filesystem, which by default, is separate from the host filesystem.

There is no "containernic" :) way to do this. Mounting host directories is just not practical, for my use cases. I could always cp files into the container, but it's kind of impractical.

I'm pretty impressed with nicolargo/glances, a cli top like app, so you know where I'm coming from.

**Comment by pj-connect** [comment]
[Check this out](https://hub.docker.com/r/pandoc/core) : 

```
docker run --rm \
       --volume "$(pwd):/data" \
       --user $(id -u):$(id -g) \
       pandoc/core README.md -o outfile.epub

```

This will convert the file README.md in the current working directory into outfile.epub. Note that Docker options go before the image name, here pandoc/core, while pandoc options come after it.

**Comment by meyayl** [comment]
Please understand that what you are looking for is not in scope.

Like I wrote in my first post: Feel free to fork the project, and modify it to your needs :)
