### ISSUE TITLE
Ngram download stalls

### ISSUE THREAD

**Issue by Unwrapped3** [meyayl/docker-languagetool#37]
Hi! The container stalls at random points when downloading ngram data, resulting in the archive being corrupted. This, in turn, prevents the container from starting:

![image](https://github.com/user-attachments/assets/9c60393d-6076-480c-a470-fd0bb03e8f03)

The internet connection is stable.  The automatic download fails around 38% for some reason - I tried it multiple times and the result is always the same. 

I would appreciate any hints on how to fix it. Thanks!

**Comment by meyayl** [comment]
The container uses whatever wget version comes with the current Alpine version. I just made a new image based on Alpine 3.20.2, which may behave differently. 

I removed my ngrams folder, and it works like a charm.

It could be anything:
- not space left in the volume
- brittle internet connection
- any hope participating in the route from your host to the download server could be flaky
- the download server might have issues.

Nothing I can reproduce or have control of.

I could try to generate and add the sha256 checksums for the files and verify that the downloaded files match the checksum before extracting them. I could retry the download up to n times if the checksum doesn't match.

**Comment by Unwrapped3** [comment]
> The container uses whatever wget version comes with the current Alpine image version. I just made a new image based on Alpine 3.20.2.
> 
> I removed my ngrams folder, and it works like a charm.
> 
> It could be anything:
> 
>     * not enough space left in the volume
> 
>     * brittle internet connection
> 
>     * any hop participating in the route from your host to the download server could be flaky
> 
>     * the download server might have issues.
> 
> 
> Nothing I can reproduce or have control of.
> 
> I could try to generate and add the sha256 checksums for the files and verify that the downloaded files match the checksum before extracting them. I could retry the download up to n times if the checksum doesn't match.

Thank you very much for your reply! Then, the issue must be local. I have decided to download the ngrams directly from [LanguageTool's developer website](https://languagetool.org/download/ngram-data/), and it works without any errors. I am not sure if they are indeed the latest — they were updated the last time on November 23, 2020 — but they work.

**Comment by meyayl** [comment]
>I have decided to download the ngrams directly from [LanguageTool's developer website](https://languagetool.org/download/ngram-data/)

Those are exactly the files the entrypoint downloads. The didn't change since I started publishing the image.
