### ISSUE TITLE
Tini related error on Raspberry pi.

### ISSUE THREAD

**Issue by nikolasdmtr** [meyayl/docker-languagetool#39]
I get a tini related error trying to deploy on Raspberry pi 4.

**Comment by meyayl** [comment]
I am surprised you even get so far: the image is x86_64 only. 

If you check “Insights” -> “Network”, I can imagine that you will be able to find a fork where someone builds and publishes an image that works on an arm device. 

Note: I am not going to support any other architectures other than x86_64. I am a strong believer of "eat our own dog food", and I don't own a pi, and as such don't want to build something that I am not using myself and can not test in case something breaks.

**Comment by nikolasdmtr** [comment]
Ah, that explains it. Thank you!
