### ISSUE TITLE
Running container is reported as unhealthy

### ISSUE THREAD

**Issue by mibere** [meyayl/docker-languagetool#4]
After starting the container it is reported as unhealthy by `docker ps`

> Up 5 minutes (unhealthy)

If I run the used health check command

`wget --quiet --post-data "language=en-US&text=a simple test" -O - http://localhost:8010/v2/check > /dev/null > 2&1`

manually I get

`[1] 2990
-bash: 1: command not found`

Maybe it was your intention to use `2>&1` instead?

**Comment by meyayl** [comment]
That indeed was a mistake, thank you for pointing it out!

**Comment by meyayl** [comment]
Fixed and pushed to DH. Much appreciated!
